### ISSUE TITLE
Niworkflows fails to install in clean virtual environment.

### ISSUE THREAD

**Issue by rwblair** [poldracklab/niworkflows#104]
Nipype dependency is not being resolved:

```
~/projects $ pip install niworkflows
Collecting niworkflows
  Using cached niworkflows-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-y4utn7fb/niworkflows/setup.py", line 11, in <module>
        from niworkflows import (__version__, __email__, __url__, __packagename__, __license__,
      File "/private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-y4utn7fb/niworkflows/niworkflows/__init__.py", line 14, in <module>
        from niworkflows import anat, common, dwi, func
      File "/private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-y4utn7fb/niworkflows/niworkflows/anat/__init__.py", line 7, in <module>
        from niworkflows.anat.skullstrip import afni_wf as skullstrip_afni
      File "/private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-y4utn7fb/niworkflows/niworkflows/anat/skullstrip.py", line 6, in <module>
        from nipype.pipeline import engine as pe
    ModuleNotFoundError: No module named 'nipype'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hw/7bn8tjn96vd58k7sg1ptt82c0000gn/T/pip-build-y4utn7fb/niworkflows/
```

**Comment by oesteban** [comment]
```
conda create -y --name testenv2 numpy scipy matplotlib pandas networkx scikit-learn && source activate testenv2 && pip install niworkflows
```
Worked for me. Could you try to check on this again?

**Comment by oesteban** [comment]
Please check and reopen if necessary @rwblair
