### ISSUE TITLE
ANTSRegistrationRPT crashes if no fixed mask is provided.

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#123]
```
Traceback (most recent call last):
  File "/home/oesteban/workspace/nipype/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/oesteban/workspace/nipype/nipype/pipeline/engine/nodes.py", line 366, in run
    self._run_interface()
  File "/home/oesteban/workspace/nipype/nipype/pipeline/engine/nodes.py", line 476, in _run_interface
    self._result = self._run_command(execute)
  File "/home/oesteban/workspace/nipype/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/home/oesteban/workspace/nipype/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/home/oesteban/workspace/nipype/nipype/interfaces/base.py", line 1728, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 72, in _run_interface
    self._generate_report()
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 166, in _generate_report
    cuts = cuts_from_bbox(mask_nii, cuts=n_cuts)
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/utils.py", line 178, in cuts_from_bbox
    ras_coords.append(apply_affine(mask_nii.affine, cross).tolist())
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nibabel/affines.py", line 84, in apply_affine
    res = np.dot(pts, rzs.T) + trans[None, :]
ValueError: shapes (1,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)
Interface ANTSRegistrationRPT failed to run.
```

**Comment by oesteban** [comment]
Fixed in 72325658db5b5ecf4fe066f88fe4398a00884f09
