### ISSUE TITLE
Nipype submodule fails when plugins are passed as string

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#179]
While building the docker image for mriqc I realized that nipype was still being installed as it is listed [here](https://github.com/poldracklab/mriqc/blob/master/mriqc/__about__.py#L55). In https://github.com/poldracklab/mriqc/pull/561 I removed that line, and now there is no top-level module for nipype. [This PR is failing](https://circleci.com/gh/oesteban/mriqc/1216?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

```
2017-06-13 17:53:15,423 workflow:ERROR Could not import plugin module: nipype.pipeline.plugins
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 562, in run
    __import__(name)
ModuleNotFoundError: No module named 'nipype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/mriqc", line 11, in <module>
    load_entry_point('mriqc===5c66495dcbf0cd661e996de13a2cbd4c5b33f72c', 'console_scripts', 'mriqc')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/mriqc/bin/mriqc_run.py", line 320, in main
    workflow.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 566, in run
    raise ImportError(msg)
ImportError: Could not import plugin module: nipype.pipeline.plugins
```
The problematic line is [linked here](https://github.com/nipy/nipype/blob/9d63943916eef02cf793e2dd8324a9c272d40610/nipype/pipeline/engine/workflows.py#L560)

**Comment by effigies** [comment]
Yeah, FMRIPREP uses some `Function` interfaces that import from `nipype`. Hence I left in the installation requirement.
