### ISSUE TITLE
Regression of int-type run entity on ReadSidecarJSON

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#306]
My latest re-implementation with pybids reintroduced this problem. A unit-test needs to be added.

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 637, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 371, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 472, in aggregate_outputs
    raise error
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 465, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'run' trait of a ReadSidecarJSONOutputSpec instance must be a unicode string, but a value of 1  was specified.
```

**Comment by oesteban** [comment]
In the meantime, if you get this error, you can easily workaround it by renaming your `run` entities to have zero padding, e.g.:
```
fmap/sub-01_run-1_phasediff.json -> fmap/sub-01_run-01_phasediff.json
fmap/sub-01_run-1_phasediff.nii.gz -> fmap/sub-01_run-01_phasediff.nii.gz
fmap/sub-01_run-2_phasediff.json -> fmap/sub-01_run-02_phasediff.json
fmap/sub-01_run-2_phasediff.nii.gz -> fmap/sub-01_run-02_phasediff.nii.gz
```

**Comment by effigies** [comment]
... Adding zeroes fixes it? pybids interprets indices (run, echo, etc.) as `int`s, so I would have imagined would still produce `int`s in this case.

**Comment by oesteban** [comment]
You are probably right, that was the case before relying on pybids. This regression is harder than that :(

**Comment by effigies** [comment]
Related: bids-standard/pybids#381

**Comment by oesteban** [comment]
The only rabbit hole I can anticipate here is that generating new paths in our derivatives datasinks will be a bit harder if the leading zeros are lost at casting.

WDTY @chrisfilo, @effigies? Do you think it would be acceptable something like?:

```
sub-01/func/sub-01_task-rest_run-01_bold.nii.gz -- derives to --> sub-01/func/sub-01_task-rest_run-1_desc-preproc_bold.nii.gz
```

If that is acceptable, then we can go for ints here right away.

**Comment by effigies** [comment]
This is the behavior encouraged by the [spec](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#participant-names-and-other-labels).

> In contrast to other labels, run and echo labels MUST be integers. Those labels MAY include zero padding, but this is NOT RECOMMENDED to maintain their uniqueness.

**Comment by oesteban** [comment]
Okay, actually I'm wrong. DerivativesDataSink is still not working atop pybids so the PR above will not modify the old behavior. I have opened #308 for that.
