### ISSUE TITLE
[BUG] urlopen in python 2 fails - '_fileobject' object has no attribute 'readinto'

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#4]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "niworkflows/data/getters.py", line 116, in get_ants_oasis_template
    md5sum='34d39070b541c416333cc8b6c2fe993c'):
  File "niworkflows/data/utils.py", line 142, in _fetch_file
    verbose=verbose)
  File "niworkflows/data/utils.py", line 157, in _fetch_file
    verbose=verbose, retry=retry + 1)
  File "niworkflows/data/utils.py", line 164, in _fetch_file
    initial_size=initial_size, verbose=verbose)
  File "niworkflows/data/utils.py", line 342, in _chunk_read_
    chunk = response.read(chunk_size)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 516, in read
    return bytes(super(HTTPResponse, self).read(amt))
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 545, in readinto
    return self._readinto_chunked(b)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 644, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/http/client.py", line 701, in _safe_readinto
    n = self.fp.readinto(mvb)
AttributeError: '_fileobject' object has no attribute 'readinto'
```

**Comment by oesteban** [comment]
This happened with the GDrive API shutting down. Not a problem anymore.
