### ISSUE TITLE
RobustMNISpatialNormalization interface failing for MNI152NLin2009cAsym

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#411]
Getting this on TACC:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 649, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 376, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 127, in _run_interface
    ants_args = self._get_ants_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 378, in _get_ants_args
    "fixed_masked.nii.gz")
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 422, in mask
    data = in_nii.get_data()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/dataobj_images.py", line 203, in get_data
    data = np.asanyarray(self._dataobj)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/numeric.py", line 553, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 355, in __array__
    raw_data = self.get_unscaled()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 350, in get_unscaled
    mmap=self._mmap)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/volumeutils.py", line 535, in array_from_file
    getattr(infile, 'name', 'object')))
OSError: Expected 17060042 bytes, got 6156601 bytes from object
 - could the file be damaged?
```

@effigies could this be that `get_data` (instead of `get_fdata`)?
```
File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 422, in mask
    data = in_nii.get_data()`
```

**Comment by oesteban** [comment]
Sorry for the noise. Indeed a corrupt file.

Deleting the corresponding templateflow item and re-downloading it before a second attempt of execution worked out.
