### ISSUE TITLE
Building MRIQC's documentation fails at importing niworkflows

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#423]
```
Warning, treated as error:
autodoc: failed to import module 'workflows' from module 'mriqc'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/project/mriqc/workflows/__init__.py", line 19, in <module>
    from .anatomical import anat_qc_workflow
  File "/root/project/mriqc/workflows/anatomical.py", line 39, in <module>
    from niworkflows.interfaces.bids import ReadSidecarJSON
  File "/usr/local/lib/python3.7/site-packages/niworkflows/interfaces/__init__.py", line 9, in <module>
    from .registration import (FLIRTRPT as FLIRT,
  File "/usr/local/lib/python3.7/site-packages/niworkflows/interfaces/registration.py", line 200, in <module>
    if LooseVersion("0.0.0") < fs.Info.looseversion() < LooseVersion("6.0.0"):
  File "/usr/local/lib/python3.7/distutils/version.py", line 52, in __lt__
```

**Comment by mgxd** [comment]
is this still an issue?

**Comment by oesteban** [comment]
If it is, it should rather be filed in mriqc
