### ISSUE TITLE
Have circle run tests in python 2.7 as well

### ISSUE THREAD

**Issue by shoshber** [poldracklab/niworkflows#45]
major changes to the python `import` system just bit us--tests were fine in python 3, not so in python 2.7

**Comment by shoshber** [comment]
@rwblair mentioned `tox` as a potential tool

**Comment by oesteban** [comment]
This issue should be split in two issues:

- Modify circle to run tests both in 2.7 and 3.5.
- The fact that tests are not passing in python 2.7.

The first issue is a desired feature for the future, I don't think it is necessary for the OHBM sprint.

The second issue requires more context: what is failing with python 2.7?. We should adopt more informative issue reporting as a best practice.

I have tried to run nosetests quickly in my python 2.7 environment and this is what I get:

```
(nipypedev-2.7) oesteban@dendrite:~/workspace/niworkflows$ nosetests .
EEEEE
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (utils.py, line 164))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/oesteban/workspace/niworkflows/niworkflows/anat/__init__.py", line 7, in <module>
    from niworkflows.anat.mni import RobustMNINormalization
  File "/home/oesteban/workspace/niworkflows/niworkflows/anat/mni.py", line 21, in <module>
    from niworkflows.common import report
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 19, in <module>
    from niworkflows.viz import utils as viz
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/__init__.py", line 5, in <module>
    from .utils import SVGNS, save_html, as_svg
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/utils.py", line 164
    plot_func(image, **plot_params, **kwargs)
                                  ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (utils.py, line 164))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/__init__.py", line 4, in <module>
    from .masks import BETRPT as BET
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/masks.py", line 4, in <module>
    from niworkflows.common import report as nrc
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 19, in <module>
    from niworkflows.viz import utils as viz
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/__init__.py", line 5, in <module>
    from .utils import SVGNS, save_html, as_svg
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/utils.py", line 164
    plot_func(image, **plot_params, **kwargs)
                                  ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (utils.py, line 164))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/__init__.py", line 5, in <module>
    from .utils import SVGNS, save_html, as_svg
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/utils.py", line 164
    plot_func(image, **plot_params, **kwargs)
                                  ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (utils.py, line 164))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 16, in <module>
    from niworkflows.interfaces.registration import FLIRTRPT
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/__init__.py", line 4, in <module>
    from .masks import BETRPT as BET
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/masks.py", line 4, in <module>
    from niworkflows.common import report as nrc
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 19, in <module>
    from niworkflows.viz import utils as viz
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/__init__.py", line 5, in <module>
    from .utils import SVGNS, save_html, as_svg
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/utils.py", line 164
    plot_func(image, **plot_params, **kwargs)
                                  ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (utils.py, line 164))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_validators.py", line 3, in <module>
    from niworkflows.common import report
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 19, in <module>
    from niworkflows.viz import utils as viz
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/__init__.py", line 5, in <module>
    from .utils import SVGNS, save_html, as_svg
  File "/home/oesteban/workspace/niworkflows/niworkflows/viz/utils.py", line 164
    plot_func(image, **plot_params, **kwargs)
                                  ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 5 tests in 0.645s

FAILED (errors=5)
```

That line seems to be python 3 compatible but not python 2 compatible.

**Comment by oesteban** [comment]
Before adding the 2.7 tests in circle, we should make sure they can be run locally (meaning, we should address #52 first). Before the BrainExtraction test, I have this so far:

```
EE
======================================================================
ERROR: test of BET's report under basic (output binary mask) conditions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 58, in test_generate_report
    'testBET.html')
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 101, in _smoke_test_report
    .format(out_report))
TypeError: unbound method assertTrue() must be called with TestCase instance as first argument (got bool instance instead)
-------------------- >> begin captured logging << --------------------
niworkflows: INFO: Generating report for BET. file "/home/oesteban/.cache/stanford-crn/mni_template_RAS/MNI152_T1_2mm.nii.gz", and mask file "/tmp/tmpuR6exn/MNI152_T1_2mm_brain_mask.nii.gz"
niworkflows: INFO: Successfully created report (/tmp/tmpuR6exn/report.html)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: if the in_file was 4d, it should be able to produce the same report
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 70, in test_generate_report_from_4d
    'testBET4d.html')
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 101, in _smoke_test_report
    .format(out_report))
TypeError: unbound method assertTrue() must be called with TestCase instance as first argument (got bool instance instead)
-------------------- >> begin captured logging << --------------------
niworkflows: INFO: Generating report for BET. file "/home/oesteban/workspace/niworkflows/mni_4d.nii.gz", and mask file "/tmp/tmpfPJJYs/mni_4d_brain_mask.nii.gz"
niworkflows: INFO: Successfully created report (/tmp/tmpfPJJYs/report.html)
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 3 tests in 513.784s

FAILED (errors=2)
```

**Comment by shoshber** [comment]
> Edit: I think `_smoke_test_report` should be also a class member of our tests, and then call `self.assertTrue`

Great idea

**Comment by rwblair** [comment]
Can we dump 2.7 support?

**Comment by oesteban** [comment]
@rwblair niworkflows supports 2.7 - I daily work on 2.7 and use it in ls5 with py2.7.

The tests do not support 2.7

**Comment by chrisfilo** [comment]
multiproc is still broken in 2.7 - I would not recommend spending time
developing for it until the bug is fixed.

Having said that I cannot imagine the multiproc bug not getting fixed and
nipype dropping 2.7 support.

**Comment by oesteban** [comment]
even with multiproc broken in nipype 2.7, I run it perfectly... And after the experience with nipype, people seem to be still stuck in 2.7.
