### ISSUE TITLE
Tests do not run in python 2.7

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#52]
```
$ nosetests .
EEE..E/home/oesteban/workspace/niworkflows/niworkflows/viz/validators.py:25: UserWarning: CSS Validator encountered the following parser errors while parsing (CSS starting `@keyf`). CSS may not be syntactically correct, and CSS Validator may not have been able to do its job. 
[ParseError(u'Parse error at 1:1, unknown at-rule in stylesheet context: @keyframe',)]
  css[:5], stylesheet.errors))
...
======================================================================
ERROR: test of BET's report under basic (output binary mask) conditions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 59, in test_generate_report
    'testBET.html')
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 78, in _smoke_test_report
    unittest.TestCase().assertTrue(os.path.isfile(out_report), 'HTML report exists at {}'
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/unittest/case.py", line 189, in __init__
    (self.__class__, methodName))
ValueError: no such test method in <class 'unittest.case.TestCase'>: runTest
-------------------- >> begin captured logging << --------------------
niworkflows: INFO: Generating report for BET. file "/home/oesteban/.cache/stanford-crn/mni_template_RAS/MNI152_T1_2mm.nii.gz", and mask file "/tmp/tmpk6LsOL/MNI152_T1_2mm_brain_mask.nii.gz"
niworkflows: INFO: Successfully created report (/tmp/tmpk6LsOL/report.html)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: if the in_file was 4d, it should be able to produce the same report
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 71, in test_generate_report_from_4d
    'testBET4d.html')
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 78, in _smoke_test_report
    unittest.TestCase().assertTrue(os.path.isfile(out_report), 'HTML report exists at {}'
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/unittest/case.py", line 189, in __init__
    (self.__class__, methodName))
ValueError: no such test method in <class 'unittest.case.TestCase'>: runTest
-------------------- >> begin captured logging << --------------------
niworkflows: INFO: Generating report for BET. file "/home/oesteban/workspace/niworkflows/mni_4d.nii.gz", and mask file "/tmp/tmpoYmTOC/mni_4d_brain_mask.nii.gz"
niworkflows: INFO: Successfully created report (/tmp/tmpoYmTOC/report.html)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test of FAST's report under basic conditions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 94, in test_generate_report
    _smoke_test_report(report_interface, 'testFast.html')
  File "/home/oesteban/workspace/niworkflows/niworkflows/tests/test_reports.py", line 78, in _smoke_test_report
    unittest.TestCase().assertTrue(os.path.isfile(out_report), 'HTML report exists at {}'
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/unittest/case.py", line 189, in __init__
    (self.__class__, methodName))
ValueError: no such test method in <class 'unittest.case.TestCase'>: runTest
-------------------- >> begin captured logging << --------------------
niworkflows: INFO: Generating report for FAST (in_files [u'/home/oesteban/workspace/niworkflows/MNI152_T1_2mm_brain.nii.gz'], segmentation /tmp/tmpikSPLS/test_seg.nii.gz, individual tissue classes [u'/tmp/tmpikSPLS/test_seg_0.nii.gz', u'/tmp/tmpikSPLS/test_seg_1.nii.gz', u'/tmp/tmpikSPLS/test_seg_2.nii.gz']).
niworkflows: INFO: Successfully created report (/tmp/tmpikSPLS/report.html)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_save_html (test_validators.TestHTMLValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/mock-1.3.0-py2.7.egg/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/lib/python2.7/site-packages/mock-1.3.0-py2.7.egg/mock/mock.py", line 1454, in __enter__
    raise TypeError("Can't pass kwargs to a mock we aren't creating")
TypeError: Can't pass kwargs to a mock we aren't creating

----------------------------------------------------------------------
Ran 9 tests in 45.089s

FAILED (errors=4)
```
Also, the test/common/test_report.py was not found by nosetests.

**Comment by shoshber** [comment]
just updating it here too, for continuity of conversation--we can rm `test/common/test_report.py`

**Comment by oesteban** [comment]
Yep, @rwblair fixed that here: https://github.com/poldracklab/niworkflows/pull/48/files#diff-eefc623ffc8016d61d0a85d393f3ae23 and that commit is now merged in master :)
