### ISSUE TITLE
ImportError: cannot import name load_img (from nilearn.image)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#79]
```
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-2.7/bin/fmriprep", line 9, in <module>
    load_entry_point('fmriprep', 'console_scripts', 'fmriprep')()
  File "/home/oesteban/workspace/fmriprep/fmriprep/run_workflow.py", line 75, in main
    create_workflow(opts)
  File "/home/oesteban/workspace/fmriprep/fmriprep/run_workflow.py", line 83, in create_workflow
    from fmriprep.workflows.base import base_workflow_enumerator
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/__init__.py", line 5, in <module>
    from fmriprep.workflows.anatomical import t1w_preprocessing
  File "/home/oesteban/workspace/fmriprep/fmriprep/workflows/anatomical.py", line 19, in <module>
    from niworkflows.interfaces.registration import RobustMNINormalizationRPT
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/__init__.py", line 4, in <module>
    from .masks import BETRPT as BET
  File "/home/oesteban/workspace/niworkflows/niworkflows/interfaces/masks.py", line 9, in <module>
    from niworkflows.common import report as nrc
  File "/home/oesteban/workspace/niworkflows/niworkflows/common/report.py", line 10, in <module>
    from nilearn.image import load_img
ImportError: cannot import name load_img
```

Also:
```
python -c "from nilearn.image import load_img"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name load_img
```
Version:
```
 python -c "import nilearn; print nilearn.__version__"
0.2.3
```

**Comment by oesteban** [comment]
Ok, seems like 0.2.6 has it. This issue would require (only) to set a minimum version for nilearn

**Comment by chrisfilo** [comment]
I'll fix it.

**Comment by oesteban** [comment]
OMG - that's fast.
